openapi: 3.2.0
info:
  title: Opik REST Is Alive API
  description: The Opik REST API is currently in beta and subject to change.
  contact:
    name: Github Repository
    url: https://github.com/comet-ml/opik
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:5173/api
  description: Local server
- url: https://www.comet.com/opik/api
  description: Opik Cloud
tags:
- name: Is Alive
paths:
  /is-alive/ping:
    get:
      operationId: isAlive
      responses:
        default:
          description: default response
          content:
            application/json: {}
      tags:
      - Is Alive
      summary: Is alive
      x-summary-source: derived
  /is-alive/ver:
    get:
      operationId: version
      responses:
        default:
          description: default response
          content:
            application/json: {}
      tags:
      - Is Alive
      summary: Version
      x-summary-source: derived
