openapi: 3.1.0
info:
  title: Opik REST Redirect API
  description: "The Opik REST API is currently in beta and subject to change. If you have any questions or feedback about the APIs, please reach out on GitHub: https://github.com/comet-ml/opik.\n\nAll of the methods listed in this documentation are used by either the SDK or the UI to interact with the Opik server. As a result,\nthe methods have been optimized for these use-cases in mind. If you are looking for a method that is not listed above, please create\nand issue on GitHub or raise a PR!\n\nOpik includes two main deployment options that results in slightly different API usage:\n\n- **Self-hosted Opik instance:** You will simply need to specify the URL as `http://localhost:5173/api/<endpoint_path>` or similar. This is the default option for the docs.\n- **Opik Cloud:** You will need to specify the Opik API Key and Opik Workspace in the header. The format of the header should be:\n\n  ```\n  {\n    \"Comet-Workspace\": \"your-workspace-name\",\n    \"authorization\": \"your-api-key\"\n  }\n  ```\n\n  The full payload would therefore look like:\n  \n  ```\n  curl -X GET 'https://www.comet.com/opik/api/v1/private/projects' \\\n  -H 'Accept: application/json' \\\n  -H 'Comet-Workspace: <your-workspace-name>' \\\n  -H 'authorization: <your-api-key>'\n  ```\n\n  Do take note here that the authorization header value does not include the `Bearer ` prefix. To switch to using the Opik Cloud in the documentation, you can\n  click on the edit button displayed when hovering over the `Base URL` displayed on the right hand side of the docs.\n"
  contact:
    name: Github Repository
    url: https://github.com/comet-ml/opik
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:5173/api
  description: Local server
- url: https://www.comet.com/opik/api
  description: Opik Cloud
tags:
- name: Redirect
  description: Redirects for SDK generated links
paths:
  /v1/session/redirect/datasets:
    get:
      tags:
      - Redirect
      summary: Create dataset redirect url
      description: Create dataset redirect url
      operationId: datasetsRedirect
      parameters:
      - name: dataset_id
        in: query
        required: true
        schema:
          type: string
          format: uuid
      - name: workspace_name
        in: query
        schema:
          type: string
      - name: path
        in: query
        required: true
        schema:
          type: string
      responses:
        '303':
          description: Redirect
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
  /v1/session/redirect/experiments:
    get:
      tags:
      - Redirect
      summary: Create experiment redirect url
      description: Create experiment redirect url
      operationId: experimentsRedirect
      parameters:
      - name: dataset_id
        in: query
        required: true
        schema:
          type: string
          format: uuid
      - name: experiment_id
        in: query
        required: true
        schema:
          type: string
          format: uuid
      - name: workspace_name
        in: query
        schema:
          type: string
      - name: path
        in: query
        required: true
        schema:
          type: string
      responses:
        '303':
          description: Redirect
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
  /v1/session/redirect/optimizations:
    get:
      tags:
      - Redirect
      summary: Create optimization redirect url
      description: Create optimization redirect url
      operationId: optimizationsRedirect
      parameters:
      - name: dataset_id
        in: query
        required: true
        schema:
          type: string
          format: uuid
      - name: optimization_id
        in: query
        required: true
        schema:
          type: string
          format: uuid
      - name: workspace_name
        in: query
        schema:
          type: string
      - name: path
        in: query
        required: true
        schema:
          type: string
      responses:
        '303':
          description: Redirect
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
  /v1/session/redirect/projects:
    get:
      tags:
      - Redirect
      summary: Create project redirect url
      description: Create project redirect url
      operationId: projectsRedirect
      parameters:
      - name: trace_id
        in: query
        required: true
        schema:
          type: string
          format: uuid
      - name: workspace_name
        in: query
        schema:
          type: string
      - name: path
        in: query
        required: true
        schema:
          type: string
      responses:
        '303':
          description: Redirect
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
components:
  schemas:
    ErrorMessage:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: string
