openapi: 3.2.0
info:
  title: Opik REST System usage API
  description: The Opik REST API is currently in beta and subject to change.
  contact:
    name: Github Repository
    url: https://github.com/comet-ml/opik
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:5173/api
  description: Local server
- url: https://www.comet.com/opik/api
  description: Opik Cloud
tags:
- name: System usage
  description: System usage related resource
paths:
  /v1/internal/usage/bi-datasets:
    get:
      tags:
      - System usage
      summary: Get datasets information for BI events
      description: Get datasets information for BI events per user per workspace
      operationId: getDatasetBiInfo
      responses:
        '200':
          description: Datasets BiInformationResponse resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BiInformationResponse'
  /v1/internal/usage/bi-experiments:
    get:
      tags:
      - System usage
      summary: Get experiments information for BI events
      description: Get experiments information for BI events per user per workspace
      operationId: getExperimentBiInfo
      responses:
        '200':
          description: Experiments BiInformationResponse resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BiInformationResponse'
  /v1/internal/usage/bi-spans:
    get:
      tags:
      - System usage
      summary: Get spans information for BI events
      description: Get spans information for BI events per user per workspace
      operationId: getSpansBiInfo
      responses:
        '200':
          description: Spans BiInformationResponse resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BiInformationResponse'
  /v1/internal/usage/workspace-span-counts:
    get:
      tags:
      - System usage
      summary: Get spans count on previous day for all available workspaces
      operationId: getSpansCountForWorkspaces
      responses:
        '200':
          description: SpanCountResponse resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpansCountResponse'
  /v1/internal/usage/bi-traces:
    get:
      tags:
      - System usage
      summary: Get traces information for BI events
      description: Get traces information for BI events per user per workspace
      operationId: getTracesBiInfo
      responses:
        '200':
          description: Traces BiInformationResponse resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BiInformationResponse'
  /v1/internal/usage/workspace-trace-counts:
    get:
      tags:
      - System usage
      summary: Get traces count on previous day for all available workspaces
      operationId: getTracesCountForWorkspaces
      responses:
        '200':
          description: TraceCountResponse resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TraceCountResponse'
components:
  schemas:
    WorkspaceTraceCount:
      type: object
      properties:
        workspace:
          type: string
        trace_count:
          type: integer
          format: int32
    SpansCountResponse:
      type: object
      properties:
        workspaces_spans_count:
          type: array
          items:
            $ref: '#/components/schemas/WorkspaceSpansCount'
    BiInformationResponse:
      type: object
      properties:
        bi_information:
          type: array
          items:
            $ref: '#/components/schemas/BiInformation'
    TraceCountResponse:
      type: object
      properties:
        workspaces_traces_count:
          type: array
          items:
            $ref: '#/components/schemas/WorkspaceTraceCount'
    WorkspaceSpansCount:
      type: object
      properties:
        workspace:
          type: string
        span_count:
          type: integer
          format: int32
    BiInformation:
      type: object
      properties:
        workspace_id:
          type: string
        user:
          type: string
        count:
          type: integer
          format: int64
