openapi: 3.1.0
info:
  title: Opik REST Guardrails API
  description: "The Opik REST API is currently in beta and subject to change. If you have any questions or feedback about the APIs, please reach out on GitHub: https://github.com/comet-ml/opik.\n\nAll of the methods listed in this documentation are used by either the SDK or the UI to interact with the Opik server. As a result,\nthe methods have been optimized for these use-cases in mind. If you are looking for a method that is not listed above, please create\nand issue on GitHub or raise a PR!\n\nOpik includes two main deployment options that results in slightly different API usage:\n\n- **Self-hosted Opik instance:** You will simply need to specify the URL as `http://localhost:5173/api/<endpoint_path>` or similar. This is the default option for the docs.\n- **Opik Cloud:** You will need to specify the Opik API Key and Opik Workspace in the header. The format of the header should be:\n\n  ```\n  {\n    \"Comet-Workspace\": \"your-workspace-name\",\n    \"authorization\": \"your-api-key\"\n  }\n  ```\n\n  The full payload would therefore look like:\n  \n  ```\n  curl -X GET 'https://www.comet.com/opik/api/v1/private/projects' \\\n  -H 'Accept: application/json' \\\n  -H 'Comet-Workspace: <your-workspace-name>' \\\n  -H 'authorization: <your-api-key>'\n  ```\n\n  Do take note here that the authorization header value does not include the `Bearer ` prefix. To switch to using the Opik Cloud in the documentation, you can\n  click on the edit button displayed when hovering over the `Base URL` displayed on the right hand side of the docs.\n"
  contact:
    name: Github Repository
    url: https://github.com/comet-ml/opik
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:5173/api
  description: Local server
- url: https://www.comet.com/opik/api
  description: Opik Cloud
tags:
- name: Guardrails
  description: Guardrails related resources
paths:
  /v1/private/guardrails:
    post:
      tags:
      - Guardrails
      summary: Create guardrails for traces in a batch
      description: Batch guardrails for traces
      operationId: createGuardrails
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GuardrailBatch_Write'
      responses:
        '204':
          description: No Content
components:
  schemas:
    GuardrailBatch_Write:
      required:
      - guardrails
      type: object
      properties:
        guardrails:
          maxItems: 1000
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/Guardrail_Write'
    Guardrail_Write:
      required:
      - config
      - details
      - entity_id
      - name
      - result
      - secondary_id
      type: object
      properties:
        entity_id:
          type: string
          format: uuid
        secondary_id:
          type: string
          format: uuid
        project_name:
          pattern: (?s)^\s*(\S.*\S|\S)\s*$
          type: string
          description: If null, the default project is used
        project_id:
          type: string
          format: uuid
        name:
          type: string
          enum:
          - TOPIC
          - PII
        result:
          type: string
          enum:
          - passed
          - failed
        config:
          $ref: '#/components/schemas/JsonNode'
        details:
          $ref: '#/components/schemas/JsonNode'
    JsonNode:
      type: object
