openapi: 3.2.0
info:
  title: Opik REST Redirect API
  description: The Opik REST API is currently in beta and subject to change.
  contact:
    name: Github Repository
    url: https://github.com/comet-ml/opik
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:5173/api
  description: Local server
- url: https://www.comet.com/opik/api
  description: Opik Cloud
tags:
- name: Redirect
  description: Redirects for SDK generated links
paths:
  /v1/session/redirect/datasets:
    get:
      tags:
      - Redirect
      summary: Create dataset redirect url
      operationId: datasetsRedirect
      parameters:
      - name: dataset_id
        in: query
        required: true
        schema:
          type: string
          format: uuid
      - name: workspace_name
        in: query
        schema:
          type: string
      - name: path
        in: query
        required: true
        schema:
          type: string
      responses:
        '303':
          description: Redirect
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
  /v1/session/redirect/experiments:
    get:
      tags:
      - Redirect
      summary: Create experiment redirect url
      operationId: experimentsRedirect
      parameters:
      - name: dataset_id
        in: query
        required: true
        schema:
          type: string
          format: uuid
      - name: experiment_id
        in: query
        required: true
        schema:
          type: string
          format: uuid
      - name: workspace_name
        in: query
        schema:
          type: string
      - name: path
        in: query
        required: true
        schema:
          type: string
      responses:
        '303':
          description: Redirect
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
  /v1/session/redirect/optimizations:
    get:
      tags:
      - Redirect
      summary: Create optimization redirect url
      operationId: optimizationsRedirect
      parameters:
      - name: dataset_id
        in: query
        required: true
        schema:
          type: string
          format: uuid
      - name: optimization_id
        in: query
        required: true
        schema:
          type: string
          format: uuid
      - name: workspace_name
        in: query
        schema:
          type: string
      - name: path
        in: query
        required: true
        schema:
          type: string
      responses:
        '303':
          description: Redirect
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
  /v1/session/redirect/projects:
    get:
      tags:
      - Redirect
      summary: Create project redirect url
      operationId: projectsRedirect
      parameters:
      - name: trace_id
        in: query
        required: true
        schema:
          type: string
          format: uuid
      - name: workspace_name
        in: query
        schema:
          type: string
      - name: path
        in: query
        required: true
        schema:
          type: string
      responses:
        '303':
          description: Redirect
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
components:
  schemas:
    ErrorMessage:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: string
