openapi: 3.2.0
info:
  title: Opik REST Assertion Results API
  description: The Opik REST API is currently in beta and subject to change.
  contact:
    name: Github Repository
    url: https://github.com/comet-ml/opik
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:5173/api
  description: Local server
- url: https://www.comet.com/opik/api
  description: Opik Cloud
tags:
- name: Assertion Results
  description: Assertion result related resources
paths:
  /v1/private/assertion-results:
    put:
      tags:
      - Assertion Results
      summary: Batch ingestion of assertion results
      description: Batch ingestion of assertion results for traces or spans
      operationId: storeAssertionsBatch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssertionResultBatch'
      responses:
        '204':
          description: No Content
components:
  schemas:
    AssertionResultBatch:
      required:
      - assertion_results
      - entity_type
      type: object
      properties:
        entity_type:
          type: string
          enum:
          - TRACE
          - SPAN
          - THREAD
        assertion_results:
          maxItems: 1000
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/AssertionResultBatchItem'
    AssertionResultBatchItem:
      required:
      - entity_id
      - name
      - source
      - status
      type: object
      properties:
        entity_id:
          type: string
          format: uuid
        project_name:
          pattern: (?s)^\s*(\S.*\S|\S)\s*$
          type: string
          description: If null, the default project is used
        project_id:
          type: string
          format: uuid
        name:
          minLength: 1
          type: string
        status:
          type: string
          enum:
          - passed
          - failed
        reason:
          type: string
        source:
          type: string
          enum:
          - ui
          - sdk
          - online_scoring
