openapi: 3.2.0
info:
  title: Opik REST Guardrails API
  description: The Opik REST API is currently in beta and subject to change.
  contact:
    name: Github Repository
    url: https://github.com/comet-ml/opik
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:5173/api
  description: Local server
- url: https://www.comet.com/opik/api
  description: Opik Cloud
tags:
- name: Guardrails
  description: Guardrails related resources
paths:
  /v1/private/guardrails:
    post:
      tags:
      - Guardrails
      summary: Create guardrails for traces in a batch
      description: Batch guardrails for traces
      operationId: createGuardrails
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GuardrailBatch_Write'
      responses:
        '204':
          description: No Content
components:
  schemas:
    JsonNode:
      type: object
    GuardrailBatch_Write:
      required:
      - guardrails
      type: object
      properties:
        guardrails:
          maxItems: 1000
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/Guardrail_Write'
    Guardrail_Write:
      required:
      - config
      - details
      - entity_id
      - name
      - result
      - secondary_id
      type: object
      properties:
        entity_id:
          type: string
          format: uuid
        secondary_id:
          type: string
          format: uuid
        project_name:
          pattern: (?s)^\s*(\S.*\S|\S)\s*$
          type: string
          description: If null, the default project is used
        project_id:
          type: string
          format: uuid
        name:
          type: string
          enum:
          - TOPIC
          - PII
        result:
          type: string
          enum:
          - passed
          - failed
        config:
          $ref: '#/components/schemas/JsonNode'
        details:
          $ref: '#/components/schemas/JsonNode'
