openapi: 3.2.0
info:
  title: Opik REST Check API
  description: The Opik REST API is currently in beta and subject to change.
  contact:
    name: Github Repository
    url: https://github.com/comet-ml/opik
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:5173/api
  description: Local server
- url: https://www.comet.com/opik/api
  description: Opik Cloud
tags:
- name: Check
  description: Access check resources
paths:
  /v1/private/auth:
    post:
      tags:
      - Check
      summary: Check user access to workspace
      operationId: checkAccess
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthDetailsHolder'
      responses:
        '204':
          description: No Content
        '401':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '403':
          description: Access forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
  /v1/private/auth/workspace:
    get:
      tags:
      - Check
      summary: User's default workspace name
      operationId: getWorkspaceName
      responses:
        '200':
          description: Authentication resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceNameHolder'
        '401':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '403':
          description: Access forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
components:
  schemas:
    WorkspaceNameHolder:
      type: object
      properties:
        workspace_name:
          type: string
    AuthDetailsHolder:
      type: object
    ErrorMessage:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: string
