openapi: 3.2.0
info:
  title: Opik REST Workspace permissions API
  description: The Opik REST API is currently in beta and subject to change.
  contact:
    name: Github Repository
    url: https://github.com/comet-ml/opik
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:5173/api
  description: Local server
- url: https://www.comet.com/opik/api
  description: Opik Cloud
tags:
- name: Workspace Permissions
  description: Workspace permissions related resources
paths:
  /v1/private/workspace-permissions:
    get:
      tags:
      - Workspace Permissions
      summary: Get workspace permissions for the authenticated user
      operationId: getWorkspaceUserPermissions
      responses:
        '200':
          description: Workspace Permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceUserPermissions'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
components:
  schemas:
    WorkspaceUserPermissions:
      type: object
      properties:
        userName:
          type: string
        workspaceName:
          type: string
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/Permission'
    Permission:
      type: object
      properties:
        permissionName:
          type: string
        permissionValue:
          type: string
    ErrorMessage:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: string
